package com.cmlex.lexer.mylexer;



public enum TokenType {
    // Keywords
    INT, FLOAT, CHAR, VOID, IF, ELSE, WHILE, FOR, RETURN, BREAK, CONTINUE,
    STRUCT, TYPEDEF, ENUM, STATIC, EXTERN, CONST, VOLATILE, SIZEOF,

    // Identifiers and literals
    IDENTIFIER, INTEGER, FLOAT_LITERAL, STRING, CHARACTER,

    // Operators
    PLUS, MINUS, STAR, SLASH, PERCENT,
    EQUAL, EQUAL_EQUAL, BANG_EQUAL, LESS, GREATER, LESS_EQUAL, GREATER_EQUAL,
    AND_AND, OR_OR, BANG, AMPERSAND, PIPE, CARET, TILDE, LESS_LESS, GREATER_GREATER,
    PLUS_PLUS, MINUS_MINUS, ARROW, DOT,

    // Punctuation
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    SEMICOLON, COMMA, COLON, ELLIPSIS,

    // Special
    EOF  // End-of-file
}